- cmd/root.go
- main.go
If customers run into issues, we want to allow them to
report issues to us. For that, we need to be sure of 
what version they are running.
I am adding a --version / -v flag to the execution.
Cobra already supports this functionality as documented
here: https://github.com/spf13/cobra/blob/main/user_guide.md#version-flag
> Add the --version / -v flag

- cmd/backup_test.go
- internal/formatter/backup.go
Fixed backup displayed expire time, as we don't have the expire time from the api we need to calculate it.
> Used Created date + retain in days for backup expire time display

- NOTICE
- go.mod
- go.sum
- internal/formatter/cloud_regions.go
As per user feedback, the country code listing don't have enough eye candy.
So, adding emoji to the describe-region country codes.
> Add emoji for Country Code flags

- cmd/backup/backup.go
- cmd/cluster/assign_nal_cluster.go
- cmd/cluster/cloud_regions.go
- cmd/cluster/create_cluster.go
- cmd/cluster/delete_cluster.go
- cmd/cluster/get_cluster.go
- cmd/cluster/instance_types.go
- cmd/cluster/pause_cluster.go
- cmd/cluster/resume_cluster.go
- cmd/cluster/unassign_nal_cluster.go
- cmd/cluster/update_cluster.go
- cmd/vpc/vpc.go
- cmd/vpcpeering/vpc_peering.go
- go.mod
- go.sum
- internal/client/client.go
- internal/cluster/cluster.go
- internal/log/log.go
The output now looks like the following:
```
bash-5.2$ make build
go build -ldflags="-X 'main.version=v0.1.0'" -o ybm
bash-5.2$ ./ybm cluster pause --cluster-name twinkling-caterpillar
Cannot pause a free tier cluster
bash-5.2$ 
```
> output only the error detail instead of the full log error message

- cmd/cluster/get_cluster.go
- internal/cluster/cluster.go
In case there is a `--cluster-name cluster`
specified for `cluster get`, it defaults to a
table view regardless of what the user specified.
Making it such that the display is detailed only if the user wants a table.
Also fixing a bug where detailed display fails if the cluster is not ready because the call to fetch the allow lists fails.
> Fix -o json with single cluster info

- cmd/cluster_test.go
- internal/client/client.go
- internal/formatter/clusters_full.go
This PR fixes two things:
* display the endpoints in the `cluster describe` view
* when the user did not run `ybm auth` and tries to run a commend, they get an ugly 401. Prompt the user to run `ybm auth`.
> Display endpoints in describe cluster view

- cmd/backup/backup.go
- cmd/cdc/cdc_stream.go
- cmd/cluster/create_cluster.go
- cmd/cluster/delete_cluster.go
- cmd/cluster/network/nal/assign_nal_cluster.go
- cmd/cluster/network/nal/unassign_nal_cluster.go
- cmd/cluster/pause_cluster.go
- cmd/cluster/read-replica/read_replica.go
- cmd/cluster/resume_cluster.go
- cmd/cluster/update_cluster.go
- cmd/vpc/peering/vpc_peering.go
- cmd/vpc/vpc.go
- go.mod
- go.sum
- internal/client/client.go
The task and entity types changed to ENUMs in the API server, hence we need to change it here as well when using the latest client.
> fix enum type

- cmd/cluster/network/endpoint/update_endpoint.go
- cmd/util/util.go
In case the user specifies an empty string, we would also send an empty string
to the backend. This would result in an issue, as it expects the SP to be an ARN
for AWS.
I added a method that does a string split while ignoring the empty items (similar
to what `StringSplitOptions.RemoveEmptyEntries` does in C#).
> PSE: Fix the case when securityPrincipals list is empty

- cmd/root.go
- go.mod
- go.sum
- internal/releases/releases.go
- internal/releases/releases_suite_test.go
- internal/releases/releases_test.go
When building, we get the tag name which is `v0.1.1`.
For some reason, goreleaser specifies the version to be vv0.1.1, 
which means that the version we keep internally
ends up being `vv0.1.1` - which is not a valid semver.
This PR hardens the comparison function by
stripping the leading `v`s and then comparing.
> Fix update prompt

- cmd/root.go
- internal/releases/releases.go
- internal/releases/releases_test.go
Currently we fetch the latest version of the CLI from Github releases for every execution of the YBM CLI. However, this can lead to a overwhelming number of calls to the Github API server during automation and other scenarios where the CLI is executed frequently leading to request denial from the Github API server. Therefore, the idea is to cache the latest version of YBM CLI from Github releases and fetch it only periodically from Github.
> Cache the latest release version locally 

- cmd/region/instance_types.go
- internal/client/client.go
The API that we are using for fetching instance types is almost deprecated (plans to deprecate it in the next 1-2 weeks).
Towards that, we want to move to the new API that is very similar in nature (just that it supports multi-geo).
> Fix instance types API

- cmd/cluster/create_cluster.go
- cmd/cluster/encryption/encryption.go
- cmd/cluster/encryption/encryptionutil.go
- go.mod
- go.sum
- internal/formatter/encryption.go
Summary:
Changes required for the recent String to Enum for CMKProviderEnum.
Testing:
Tested manually by creating EAR enabled cluster with AWS CMK Config.
> [CLOUDGA-13615] Fixed CMK related error

- cmd/backup_test.go
- cmd/cluster_test.go
- cmd/cmd_suite_test.go
- cmd/test/fixtures/account.json
- cmd/test/fixtures/projects.json
- cmd/vpc_test.go
- internal/client/client.go
listProjects() API requires the permission PROJECT.READ
Api keys with custom roles that do not have PROJECT.READ will not be able to be used with CLI (forbidden errors)
ProjectData has been added to the response of listAccounts() API (which is free from RBAC)
This PR consumes that for the CLI auth client
Test plan:
Tested locally with API keys having custom roles.
P.S. can you also help with the test failures?
> [CLOUDGA-13718] Get project ID for CLI auth client from an API listAccounts API

- cmd/cluster/encryption/encryption.go
Summary:
Updating KMS Provider is restricted during updateCmk.
Testing:
Tested manually.
> [CLOUDGA-13901] Restrict updating KMS provider during updateCmk

- .gitignore
- cmd/cluster/create_cluster.go
- cmd/cluster/read-replica/read_replica.go
- cmd/cluster/update_cluster.go
- cmd/cluster_test.go
- docs/ybm_cluster_create.md
- docs/ybm_cluster_read-replica_create.md
- docs/ybm_cluster_read-replica_update.md
- docs/ybm_cluster_update.md
- go.mod
- go.sum
- internal/client/client.go
- internal/formatter/clusters.go
- internal/formatter/read_replica.go
Changes to create cluster, create read replica, edit cluster, edit read replica tasks to allow passing in disk iops.
Changes to list cluster, describe cluster formatting to display disk IOPS.
Changes to list cluster/rr, describe cluster -- now shows per-node resources rather than total resources.
Updated docs, fixed up broken tests.
> [CLOUDGA-12756] CLI changes for aws custom disk IOPS

- .goreleaser.yml
When we have multiple tags for the same commit (`v0.1.1-rc1` and `v0.1.1`), goreleaser runs into issues because it always picks the tags in alphanumeric order (so it picks `v0.1.1-rc1` for both releases). GitHub complains that the package already exists, so it refuses to upload.
Also, add a Changelog for releases.
> Multiple tags for same commit

- cmd/api_key/api_key.go
- cmd/role/role.go
- cmd/test/fixtures/account.json
- cmd/test/fixtures/projects.json
- cmd/user/user.go
- cmd/util/util.go
- docs/ybm_api-key_create.md
- docs/ybm_cluster_create.md
- docs/ybm_cluster_update.md
- docs/ybm_region_instance_list.md
- docs/ybm_region_list.md
- docs/ybm_role_create.md
- docs/ybm_user_invite.md
- docs/ybm_vpc_create.md
- go.sum
- internal/client/client.go
There are some permissions tagged as "SENSITIVE" (eg. API_KEY.CREATE, ROLE.CREATE etc)
We need to check for these permissions in the following cases:
1. {create role, update role} commands- if any of the input permissions are sensitive permissions, we have to require confirmation
2. {invite user, update user, create API Key}  commands- if any of the roles provided for these operations contain sensitive permissions, we have to require confirmation
> [CLOUDGA-14116] Add sensitive permission check during user, role, api key ops

- cmd/cdc/cdc_sink.go
- cmd/cdc/cdc_stream.go
- cmd/cluster/network/endpoint/delete_endpoint.go
- cmd/cluster/network/endpoint/describe_endpoint.go
- cmd/cluster/network/endpoint/update_endpoint.go
- cmd/cluster/read-replica/read_replica.go
- cmd/nal/network_allow_list.go
- internal/client/client.go
Remove unecessary information, just return what the api told us.
At the same time fix some static check, "error strings should not be capitalized" see https://staticcheck.io/docs/checks#ST1005
> Remove calling api from error

- go.mod
- go.sum
- internal/formatter/roles.go
Some fields are going to be removed from RoleData. Removing usages of such fields. (high level fields will be removed. All the information will now only be under "spec" and "info")
> Use non deprecated description field from roles response

- go.mod
- go.sum
Summary:
Encryption commands are failing with the error: `DISABLED is not a valid CMKStatusEnum`. 
Updated the go managed client version to fix the issue.
> [CLOUDGA-14833] Update go managed version to fix cmk error

- cmd/cluster/create_cluster.go
- cmd/util/feature_flags.go
- docs/ybm_cluster_create.md
- internal/client/client.go
Summary:
Adding support for `enterprise-security` flag which is part of createClusterRequest (CreateClusterRequest --> ClusterSpec --> ClusterInfo --> enterprise_security) for scrum: enabling PCI-DSS in YBM.
Test Plan:
created a cluster using the below command:
`./ybm cluster create     --cluster-name=test-cluster1 --enterprise-security     --credentials=username=admin,password=YBM.Is.Always.Great!`
> [CLOUDGA-14133] Add support for enterprise-security cluster setting

- cmd/cluster/create_cluster.go
- cmd/cluster/update_cluster.go
- cmd/test/fixtures/list-clusters.json
- cmd/test/fixtures/one-cluster.json
- cmd/test/fixtures/pause-cluster.json
- cmd/test/fixtures/paused-cluster.json
- cmd/test/fixtures/pausing-cluster.json
- cmd/test/fixtures/resume-cluster.json
- cmd/test/fixtures/resume-queue-cluster.json
- cmd/util/feature_flags.go
- cmd/util/util.go
- docs/ybm_cluster_create.md
- docs/ybm_cluster_encryption.md
- docs/ybm_cluster_encryption_update-state.md
- docs/ybm_cluster_update.md
- internal/client/client.go
- internal/formatter/clusters.go
- internal/formatter/clusters_full.go
This PR adds functionality for specifying the number of faults to tolerate for the domain specified by the fault tolerance. It also adds another functionality of explicitly showing the preferred region, if present using a star.
> [CLOUDGA-15694] Add support fror RF5/RF7 clusters

- cmd/root.go
- cmd/usage/usage.go
- docs/ybm.md
- docs/ybm_usage.md
- docs/ybm_usage_get.md
- go.mod
- go.sum
- internal/client/client.go
Added billing usage API support to CLI. 
This API lets the user track the billing usage between the specified date interval by showing usage across 8 billing dimensions.
The data is exported as csv or json. 
The command takes the following inputs from the user:
1. `Start date and end date`: _Mandatory_ parameters in two supported formats : `yyyy-MM-dd`  or  `RFC3339 format` (e.g., '2023-09-01T12:30:45.000Z')`
2. `Format`: _Optional_ parameter that specifies the output format of the exported data - csv or json. 
Default value: `csv`
3. `Output`: _Optional_ parameter that specified the name of the output file. 
Default value: `usage`.
4. `cluster-name`: _Optional_ list parameter for cluster names. If specified, then the usage data is aggregated across these clusters.
Default value: `null`. …
> [CLOUDGA-16256] Added billing usage API support to cli 

- cmd/test/fixtures/list-clusters-date-range.json
- cmd/test/fixtures/usage-data.json
- cmd/usage/usage.go
- cmd/usage_test.go
- docs/ybm_usage_get.md
- go.mod
- go.sum
Summary:
This PR contains the fix for the following :
1. OS did not show the filename extension along with the filename. 
2. CSV data was inconsistent with JSON
It also adds a --force flag which can overwrite the file if it already exists.
`
./ybm usage get --start 2022-10-12T15:30:00Z --end 2022-10-20T15:30:00Z --output-format csv --force
`
> Spend Tracking : Refactoring and added UTs for spend tracking

- cmd/cluster/create_cluster.go
- cmd/cluster/encryption/encryption.go
- cmd/cluster/encryption/encryptionutil.go
- docs/ybm_cluster_create.md
- docs/ybm_cluster_encryption_update.md
- docs/ybm_usage_get.md
- internal/formatter/encryption.go
Summary:
Add support for the following operations for Azure CMK.
`ybm cluster create --encryption-spec provider=AZURE,azu-client-id=<client-id>,azu-client-secret=<client-secret>,azu-tenant-id=<tenant-id>,azu-key-name=<key-name>,azu-key-vault-uri=<key-vault-uri>
`
`ybm cluster describe --cluster-name test-cluster-azure`
`ybm cluster encryption update --encryption-spec provider=AZURE,azu-client-id=<client-id>,azu-client-secret=<client-secret>,azu-tenant-id=<tenant-id>,azu-key-name=<key-name>,azu-key-vault-uri=<key-vault-uri>`
`ybm cluster encryption update-state --cluster-name test-cluster-arishta --enable`
> [CLOUDGA-17496] Add support for Azure CMK 

- cmd/backup_shedule_test.go
- internal/formatter/backup_policy_list.go
The retention period will now be displayed as follows:
```
bash-5.2$ ./ybm backup policy list --cluster-name=loyal-mackerel
Time Interval(days)   Days of the Week   Backup Start Time   Retention Period(days)
1                     NA                 NA                  8
```
> Display retention period for backup policies

- cmd/cluster/create_cluster.go
- cmd/cluster/update_cluster.go
- cmd/util/feature_flags.go
- go.mod
- go.sum
- internal/client/client.go
- internal/formatter/clusters_full.go
- internal/formatter/instance_types.go
- Added support for asymmetric geo-partitioned cluster creation (different regions can now have different num-cores, disk-size-gb, disk-iops for different regions - only for geo-partitioned clusters)
- New flows are hidden behind the ASYMMETRIC_GEO feature flag
- Successfully created, updated, and described asymmetric geo cluster
- Correctly fails when attempting to create asymmetric synchronous cluster
The new payloads look like:
```
./ybm cluster create --cluster-name asymmetric-geo-cli-2 --credentials username=vm,password=pwd --cloud-provider AWS --cluster-tier Dedicated --fault-tolerance REGION --region-info region=us-west-2,num-nodes=1,vpc=aws-west-2,num-cores=2 --region-info region=us-east-2,num-nodes=1,vpc=aws-east-2,num-cores=4 --region-info …
```
> [CLOUDGA-18071] CLI support for asymmetric geo-partitioned cluster creation

- .gitignore
- cmd/backup_shedule_test.go
- cmd/db_audit_logs_exporter/db_audit_logs_exporter.go
- cmd/db_audit_logs_exporter_test.go
- cmd/root.go
- cmd/test/fixtures/db-audit-data.json
- cmd/test/fixtures/list-db-audit.json
- go.mod
- go.sum
- internal/client/client.go
- internal/formatter/db_audit_logs_exporter.go
- internal/formatter/formatter.go
Summary:
This PR add support for 2 operations of DB-audit: associate a db-audit configuration to a cluster and list assoicated DB audit config on a cluster.
Test Plan:
Manually tested the operations, working as expected.
CLI logs ---
```
[rkumar@dev-server-rkumar-31 ybm-cli]$ ./ybm cluster list
A newer version is available. Please upgrade to the latest version v0.1.18
Name             Tier        Version        State         Health    Provider   Regions     Nodes     Node Res.(Vcpu/Mem/DiskGB/IOPS)
polite-chicken   Dedicated   2.18.5.0-b93   CONFIGURING   ❓        AWS        us-east-1   3         4 / 16GB / 200GB / 3000
[rkumar@dev-server-rkumar-31 ybm-cli]$ ./ybm db-audit list --cluster-id=7bb68af6-0875-42e0-8665-dcf634ed9fd1
A newer version is available. Please upgrade to the latest …
```
> Add support for db-audit logging (create and list)

- cmd/cluster/update_cluster.go
- internal/client/client.go
In an edit case, we should be using a different API to get the available node configurations to use. This PR does that and resolves https://yugabyte.atlassian.net/browse/CLOUDGA-19819.
**Test Plan**
```
daniel@da-mbp-y7d9w ybm-cli (CLOUDGA-19819) $ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
daniel@da-mbp-y7d9w ybm-cli (main) $ make build
go build -ldflags="-X 'main.version=v0.1.0'" -o ybm
daniel@da-mbp-y7d9w ybm-cli (main) $ ./ybm cluster update --cluster-name rpendse-test-need-prod-global --region-info region=asia-northeast1,num-nodes=3,vpc=need-regions,num-cores=4,disk-size-gb=100 --region-info region=asia-east1,num-nodes=3,vpc=need-regions,num-cores=2,disk-size-gb=100 --region-info …
```
> [CLOUDGA-19819] Set correct memory size in edit flow

- cmd/db_audit_logs_exporter/db_audit_logs_exporter.go
- cmd/db_audit_logs_exporter_test.go
- docs/ybm_db-audit-logs-exporter_unassign.md
- docs/ybm_db-audit-logs-exporter_update.md
- internal/client/client.go
Summary:
This PR add support for 2 operations of DB-audit: update a DB audit config applied on a cluster and remove a config entirely from a cluster.
Test Plan:
Manually tested the operations, working as expected. Added UTs
CLI logs/usage ---
```
rkumar@dev-server-rkumar-31 ybm-cli]$ ./ybm db-audit-logs-exporter unassign --cluster-id=98096a41-9bf6-4421-a9fc-274df53eb9d4 --export-config-id=60dc5a8d-d89c-49bd-abe0-ee2b6ab16149
A newer version is available. Please upgrade to the latest version v0.1.18
? Are you sure you want to unassign DB audit config: 60dc5a8d-d89c-49bd-abe0-ee2b6ab16149 Yes
Deleting Db Audit Logs Exporter Config 60dc5a8d-d89c-49bd-abe0-ee2b6ab16149
[rkumar@dev-server-rkumar-31 ybm-cli]$ ./ybm db-audit-logs-exporter update --cluster-id=a37b4f18-7f55-4a7a-846a-ae8361b5ea7d …
```
> [CLOUDGA-18204] Add support for db-audit (update and remove)

- cmd/db_audit_logs_exporter/db_audit_logs_exporter.go
- cmd/db_audit_logs_exporter_test.go
- cmd/test/fixtures/list-telemetry-provider.json
This change replaces `integration-id` with `integration-name` in all the DB audit commands. This is being done for better user experience.
Added UTs for the change.
Manually tested the commands.
> [CLOUDGA-20571] Add support for telemetry provider access by name

- cmd/db_audit_logs_exporter/db_audit_logs_exporter.go
- cmd/db_audit_logs_exporter_test.go
- cmd/test/fixtures/db-audit-data.json
- cmd/test/fixtures/list-db-audit.json
This change replaces `cluster-id` with `cluster-name` in DB audit commands. This is done to maintain uniformity with other commands
Added UTs for the change.
Verified docs by turning on the feature flag
Manually tested the commands
> [CLOUDGA-20741] Add support for cluster-name in DB audit

- cmd/db_audit_logs_exporter/db_audit_logs_exporter.go
- cmd/db_audit_logs_exporter_test.go
This PR adds wait to assign,unassign,delete commands for DB audit logging.
Also, improves error logging in unassign command.
Manually tested all the commands with `--wait` flag. Refer the below screenshot for each usage.
Assign:
Update:
Unassign:
> [CLODUGA-20271] Add wait for DB audit commands

- cmd/cluster/update_cluster.go
- internal/client/client.go
Sometimes, when the cluster spec doesn't change, no task is spawned. In such cases, we need not wait for task completion.
> Don't wait for task when it is not created

- cmd/cluster/connection-pooling/connection_pooling.go
- Closes CLOUDGA-23292
- Tested help command
> [CLOUDGA-23292] : Add cluster-name flag to commands to show up in help

- cmd/cluster/cluster.go
- cmd/cluster/log-exporter/query_log_exporter.go
- cmd/db_query_logs_exporter_test.go
- cmd/test/fixtures/db-query-log-exporter-custom.json
- cmd/test/fixtures/db-query-log-exporter-describe-resp.json
- cmd/test/fixtures/db-query-log-exporter-update-config-resp.json
- cmd/test/fixtures/db-query-log-exporter.json
- cmd/util/feature_flags.go
- go.sum
- internal/client/client.go
- internal/formatter/db_query_log_exporter.go
Added support for DB Query logs exporter(https://docs.yugabyte.com/preview/yugabyte-cloud/cloud-monitor/logging-export/)
- Added support for 4 subcommands for db query logging:
- Enable logging
- Disable logging
- Describe config
- Update logging config
- Added unit test for all commands
```shell
~/Developer/ybm-cli on feat/db_query_log_exporter                                                                                                       took 4s at 12:21:08
> make build && ./ybm cluster db-query-logging enable \
--cluster-name "bhupendray-cluster" \
--integration-name bhupendray-datadog-logging \
--log-line-prefix "%m :%r :%u @ %d :[%p] : %a :" \
--log-min-duration-statement 30 \
--log-connections true \
--log-duration false \
--log-error-verbosity DEFAULT \
--log-statement MOD
go …
```
> [Feature] Add support for PG Query Log exporter

- cmd/integration/integration.go
- cmd/integration_test.go
- go.mod
- go.sum
[CLOUDGA-24221](https://yugabyte.atlassian.net/browse/CLOUDGA-24221) : Updated create integration success message.
`--output=table` :
```
$ ybm integration create --config-name=lit-cli-55e7cjnk-integration --type=DATADOG --wait=false --datadog-spec=a
pi-key=f6f68b7425d28d5fa06d9336e56da125,site=datadoghq.com
A newer version is available. Please upgrade to the latest version v0.1.20
The Integration lit-cli-55e7cjnk-integration has been created
ID                                     Name                           Type      Site            ApiKey
36f3ea41-3058-465e-95f6-9191920f009a   lit-cli-55e7cjnk-integration   DATADOG   datadoghq.com   f6XXXXXXXXXXXXXXXXXXXXXXXXXXXX25
$
```
`--output=json` :
```
$ ybm integration create --config-name=lit-cli-65e7cjnk-integration --type=DATADOG …
```
> [CLOUDGA-24221] Updated create integration success message.

- cmd/db_audit_logs_exporter/db_audit_logs_exporter.go
- cmd/db_audit_logs_exporter_test.go
- cmd/test/fixtures/db-audit-data2.json
Removed `exporter_id` from db audit log `update` and `unassign` commands. 
New `update` command and output: 
```shell
./ybm db-audit-logs-exporter update \
--integration-name=dd-datasource-example \
--ysql-config="log_catalog=false,log_client=true,log_level=NOTICE,log_relation=true,log_parameter=false,log_statement_once=true" \
--statement_classes="READ,WRITE" \
--cluster-name=creative-guppy
The db audit exporter config 5ba96783-d0de-442e-ba6b-aec76c232611 is being updated
ID                                     Date Created               Cluster ID                             Integration ID                         State     Ysql Config
5ba96783-d0de-442e-ba6b-aec76c232611   2024-10-15T17:08:58.766Z   258c8f4f-2844-4517-8034-6dac78a4d091   a4240ad7-b28d-4699-9433-4745c34b6a83   ACTIVE …
```
> [CLOUDGA-23796] Remove exporter id from db audit log update and unassign commands

- cmd/cluster/log-exporter/query_log_exporter.go
- cmd/db_query_logs_exporter_test.go
- cmd/util/feature_flags.go
Added support for wait in Database query logging subcommands.
```shell
./ybm cluster db-query-logging enable --cluster-name "splendid-bandicoot" --integration-name nuij --wait
```
> Added support for wait in Database query logging subcommands

- cmd/dr/config/config.go
- cmd/dr/config/create_dr.go
- cmd/dr/config/delete_dr.go
- cmd/dr/config/describe_dr.go
- cmd/dr/config/list_dr.go
- cmd/dr/config/update_dr.go
- cmd/dr/failover_dr.go
- cmd/dr/pause_dr.go
- cmd/dr/restart_dr.go
- cmd/dr/resume_dr.go
- cmd/dr/switchover_dr.go
- cmd/root.go
- docs/ybm_dr.md
- docs/ybm_dr_config.md
- docs/ybm_dr_config_create.md
- docs/ybm_dr_config_delete.md
- docs/ybm_dr_config_describe.md
- docs/ybm_dr_config_list.md
- docs/ybm_dr_config_update.md
- docs/ybm_dr_failover.md
- docs/ybm_dr_pause.md
- docs/ybm_dr_resume.md
- docs/ybm_dr_switchover.md
```
./ybm dr config create --name first-dr --source-cluster brilliant-partridge --target-cluster passionate-coyote --databases test1
./ybm dr config list
./ybm dr config describe --config first-dr
./ybm dr config delete --config first-dr
./ybm dr config update --config sample-config --databases test1,test2
./ybm dr switchover --config sample-config
./ybm dr failover --config sample-config-final-srinivas --safetimes test1=1729716937,test2=1729716937
./ybm dr restart --config sample-config-final-srinivas --databases test1,test2
./ybm dr pause --config sample-config-final-srinivas --duration 5
./ybm dr resume --config sample-config-final-srinivas
```
> Redesign DR commands to be more meaningful

- cmd/cluster/create_cluster.go
- go.mod
- go.sum
Changed CLI cluster creation to use b64 encoded db credentials
> [CLOUDGA-23990] Base64 encode db credentials in create cluster request

- cmd/integration/integration.go
- cmd/integration_test.go
- cmd/test/fixtures/metrics-exporter-victoriametrics.json
- internal/formatter/telemetry_provider.go
```shell
~/code/ybm-cli on CLOUDGA-24744 *5 ?1                                                                                                                          at 14:33:16
> mb && ./ybm integration create --config-name vm-test --type VICTORIAMETRICS  --victoriametrics-spec endpoint=http://victoriametrics.yourcompany.com
go build -ldflags="-X 'main.version=v0.1.0'" -o ybm
you are using insecure api endpoint http://127.0.0.1:5678
The Integration vm-test has been created
ID                                     Name      Type              Endpoint
8c02a496-5032-4a29-84fd-3838b901af09   vm-test   VICTORIAMETRICS   http://victoriametrics.yourcompany.com
```
```shell
~/code/ybm-cli on CLOUDGA-24744 *5 ?1 …
```
> [CLOUDGA-24744] Add support for integration type VICTORIAMETRICS

- Makefile
- cmd/cluster/create_cluster.go
- go.mod
- go.sum
- internal/client/client.go
Tested by running: 
```
./ybm cluster create --cluster-name daniel-test-cli --credentials username=admin,password=P@ssword1 --cloud-provider GCP --cluster-tier Dedicated --region-info region=northamerica-northeast2,num-nodes=3,num-cores=2,disk-size-gb=100
```
This PR depends on https://github.com/yugabyte/yugabyte-cloud/pull/18615.
> [CLOUDGA-24851] Remove root node info from cluster creation

- cmd/integration_test.go
- internal/formatter/telemetry_provider.go
Remove ID from `integration` cmd output.
```shell
~/code/ybm-cli on main *5 ?1                                                                                                                               INT at 16:48:46
> mb && ./ybm integration create --config-name vm-test-old --type VICTORIAMETRICS  --victoriametrics-spec endpoint=http://victoriametrics.yourcompany.com
go build -ldflags="-X 'main.version=v0.1.0'" -o ybm
The Integration vm-test-old has been created
ID                                     Name          Type              Endpoint
d1aa69d2-cf17-4049-94f0-f8cf87120b4c   vm-test-old   VICTORIAMETRICS   http://victoriametrics.yourcompany.com
```
```shell
> mb && ./ybm integration create --config-name vm-test-new --type VICTORIAMETRICS  --victoriametrics-spec …
```
> CLOUDGA-24211 Remove ID from integration cmd output

- README.md
Added new command implementation checklist doc.
> Added new command implementation checklist doc

- cmd/metrics_exporter/metrics_exporter.go
- go.mod
- go.sum
Added deprecation messages for metrics export commands
```
./ybm metrics-exporter list
Command "list" is deprecated, use "integration list" instead.
This command was deprecated 2024-11-30 and will be supported until 2025-2-28.
Name              Type
yash-dpn          DATADOG
prometheus-full   VICTORIAMETRICS
> Added deprecation messages for metrics export commands

- cmd/integration/integration.go
- Fix error message for accepted sinks to include VM and Prometheus.
```shell
~/code/ybm-cli on main *5 !1 ?1                                                                                                                                at 19:35:17
> mb && ./ybm integration create --config-name vm-test-old \
--type NEWRELIC \
--victoriametrics-spec endpoint=http://victoriametrics.yourcompany.com
only datadog, grafana, googlecloud, prometheus, victoriametrics or sumologic are accepted as third party sink for now%
```
> [CLOUDGA-25250] Fix error message for accepted sinks

- cmd/cluster/pitr-config/pitr_config_ops.go
- cmd/pitr_config_test.go
- cmd/test/fixtures/create-cluster-pitr-config.json
- go.mod
- go.sum
- internal/client/client.go
Change the create pitr-config command to work with updated API that takes in multiple config creation requests. Take the params as a string array and do required param validations for each config. 
Test plan:
1. Tested manually-
2. UTs
> Bulk PITR config creation

- cmd/api_key/api_key.go
- cmd/api_key_test.go
- cmd/test/fixtures/get-or-create-api-key.json
- cmd/test/fixtures/list-api-keys-with-allow-list.json
- cmd/test/fixtures/list-api-keys.json
- cmd/util/feature_flags.go
- go.mod
- go.sum
- internal/client/client.go
- internal/formatter/api_keys.go
- Added an argument to optionally associate allow lists in CREATE API keys command.
- Show allow lists in LIST API keys command.
- In list API keys cmd, only list ACTIVE API keys by default. Currently it shows revoked/expired keys as well.
- Added tests for API key commands.
- This whole allow list argument and output column is under feature flag.
```shell
export YBM_FF_API_KEY_ALLOW_LIST=true
```
```shell
> mb && ./ybm api-key create --name admin-nal --duration 1 --unit hours --role-name Viewer --network-allow-lists "fsdfs,my-mac"
Name        Role      Status    Created By   Date Created               Last Used      Expiration                    Allow List
admin-nal   Viewer    ACTIVE    working      2025-01-15T07:12:32.768Z   Not yet used   2025-01-15T08:12:32.768131Z   my-mac, fsdfs …
```
> [CLOUDGA-25136] Support to associate allow list with API keys

- cmd/api_key/api_key.go
- cmd/api_key_test.go
- cmd/util/feature_flags.go
- docs/ybm_api-key_create.md
- internal/formatter/api_keys.go
- internal/formatter/network_allow_list.go
- [CLOUDGA-25138] Show api keys associated to an allow list in LIST AL cmd
- Remove FF for api key allow list
```shell
~/code/ybm-cli on CLOUDGA-25138-fix *6 ?6                                                                                                             took 27s at 10:35:21
> mb && ./ybm network-allow-list list
Name      Description                       Allow List          Clusters   API keys
now                                         103.175.100.75/32              test-key,hello
my-mac    Allow list for my local machine   103.175.100.49/32              vaccextvpe,admin-nal-1ff3
```
> [CLOUDGA-25138] Show api keys associated to an allow list in LIST AL cmd

- cmd/cluster/pitr-config/pitr_config_ops.go
- cmd/pitr_config_test.go
- cmd/test/fixtures/clone-now-ysql-database.json
- cmd/test/fixtures/clone-ysql-database-via-pitr-config.json
- cmd/test/fixtures/create-cluster-pitr-config.json
- cmd/test/fixtures/get-ycql-pitr-config.json
- cmd/test/fixtures/get-ysql-pitr-config.json
- cmd/test/fixtures/list-cluster-pitr-configs.json
- cmd/test/fixtures/update-cluster-pitr-config.json
- cmd/util/feature_flags.go
- go.mod
- go.sum
- internal/client/client.go
- internal/formatter/pitr_configs.go
1. Create PITR config API now takes DB ID instead of <DB name, type>
2. Add support for update PITR config command
3. Add support for clone via PITR config command
Test plan:
Tested all flows manually.
UTs for clone via PITR and update PITR
> Update create PITR spec with new request format, add update PITR and clone via PITR commands

- internal/client/client.go
DiskIops is a struct with type:
```
type NullableInt32 struct {
value *int32
isSet bool
}
```
Thus when comparing `OptionalNodeInfo` using `==`, it is actually comparing the addresses of the diskIops field rather than the int32 value itself. This PR fixes that by adding an equals method that de-references the pointer and compares that instead.
> [CLOUDGA-26365] Fix comparison of regional OptionalClusterNodeInfo

- internal/client/client.go
- [CLOUDGA-26189] Use new API's for get instance-types, cloud-regions & node-configs.
Tested via running the below two commands and verifying the API call(via MITM proxy):
```sh
$ ./ybm region list --cloud-provider AWS
$ ./ybm region instance list --cloud-provider AWS --region ap-south-1
```
> [CLOUDGA-26189] Use new API's get instance-types, cloud-regions & node-configs

- cmd/cluster/pitr-config/pitr_config_ops.go
- go.mod
- go.sum
Take clone time in millis as long instead of string which is making the API call fail
> Take clone time in millis as long instead of string which is making the API call fail

- cmd/cluster/pitr-config/pitr_config_ops.go
- cmd/pitr_config_test.go
Improve error message for clone to point in time without existing PITR config
> [CLOUDGA-26718] Improve error message for clone to point in time without existing PITR config

- cmd/cluster/update_cluster.go
[CLOUDGA-29108] Add interactive confirmation dialogue about disabling backup replication
Also added force flag to bypass the prompt for non-interactive usage
When replication is enabled on YBM but flag not passed on CLI:
```bash
$./ybm cluster update --cluster-name gp-cli --region-info region=asia-east2,num-nodes=1,num-cores=2,disk-size-gb=50,vpc=gcp --region-info region=asia-northeast3,num-nodes=1,num-cores=2,disk-size-gb=50,vpc=gcp --region-info region=europe-central2,num-nodes=1,num-cores=2,disk-size-gb=50,vpc=gcp
A newer version is available. Please upgrade to the latest version v0.1.27
? The field 'backup-replication-gcp-target' is not passed for the regions. This will disable backup replication for cluster gp-cli : Are you sure you want to proceed? No
command aborted
```
<br>With …
> [CLOUDGA-29108] Add interactive confirmation dialogue about disabling backup replication

- docs/ybm_cluster.md
- docs/ybm_cluster_connection-pooling.md
- docs/ybm_cluster_connection-pooling_disable.md
- docs/ybm_cluster_connection-pooling_enable.md
- docs/ybm_cluster_create.md
[CLOUDGA-29147](https://yugabyte.atlassian.net/browse/CLOUDGA-29147) : CLI docs for Enable-Disable Connection Pooling.
> [CLOUDGA-29147] CLI docs for Enable-Disable Connection Pooling.
