yugabyte/ybm-cli

cmd/configure.go

Added apiKey as secret.
Remove host configuration display

Refactor configure

---

NOTICE
cmd/configure.go
cmd/util/util.go
cmd/util_test.go
cmd/vpc/vpc.go
cmd/vpcpeering/vpc_peering.go
go.mod
go.sum

Added CIDR validation

---

cmd/cluster_test.go
internal/formatter/clusters.go
internal/formatter/clusters_full.go

Added cluster view and updated tests

Added tiers in cluster view

---

cmd/backup/backup.go

Update backup retention descriptions.

Added in days and default retention for backup.

---

cmd/backup/backup.go
cmd/cluster/create_cluster.go

Update doc strings for cluster create and for backup.

Update strings for help

---

NOTICE
cmd/backup_test.go
go.mod
internal/formatter/backup.go
internal/formatter/formatter.go
internal/formatter/formatter_suite_test.go
internal/formatter/formatter_test.go

Add function to Truncate char.
Limit to 10 for backup descriptions

Truncate backup description to 10 chars

---

cmd/test/fixtures/vpc-gcp-global.json
cmd/vpc_test.go
internal/client/client.go
internal/formatter/vpc.go

Trim regions for vpc

---

cmd/backup/backup.go
cmd/backup_test.go
cmd/cdc/cdc_sink.go
cmd/cdc/cdc_stream.go
cmd/cluster/describe_cluster.go
cmd/cluster/get_cluster.go
cmd/cluster/list_cluster.go
cmd/cluster_test.go
cmd/nal/network_allow_list.go
cmd/readreplica/read_replica.go
cmd/vpc/vpc.go
cmd/vpc_test.go
cmd/vpcpeering/vpc_peering.go
go.mod
go.sum

Based on feedback, we need to distinguish between
cases when the user wants to list the objects
and when the user wants to describe a single object.

Add the list/describe commands

---

NOTICE
cmd/cluster/cluster.go
cmd/cluster/node/list_nodes.go
cmd/cluster/node/node.go
cmd/cluster_test.go
cmd/test/fixtures/nodes.json
go.sum
internal/client/client.go
internal/cluster/cluster.go
internal/formatter/clusters_full.go
internal/formatter/formatter_test.go
internal/formatter/nodes.go

Added Nodes listing command 
Added Nodes listing in the cluster view

Add Nodes listing

---

internal/client/client.go

Fix small typos

---

cmd/cluster/read-replica/read_replica.go
cmd/cluster/read-replica/read_replica_suite_test.go
cmd/cluster/read-replica/read_replica_test.go

Fixed casting issue.
Open function for easier testing.

Fixed issues with read replica

---

cmd/cluster/read-replica/read_replica.go
cmd/cluster/update_cluster.go
go.mod
go.sum
internal/client/client.go

Two things are implemented in this PR:
1. Updating a cluster with a new name
2. Fixing a bug related to read replication creation and update

support new name for cluster, fix read replica bug

---

README.md
cmd/cluster/create_cluster.go
cmd/cluster/read-replica/read_replica.go
cmd/cluster/update_cluster.go
internal/client/client.go
internal/releases/releases_test.go

Use `cloud-provider` everywhere.
Doc need to be updated as well.

Use Cloud provider everywhere

---

README.md
cmd/vpc/vpc.go

Add missing cloud provider

---

NOTICE
cmd/backup/backup.go
cmd/cluster/delete_cluster.go
cmd/cluster/network/endpoint/delete_endpoint.go
cmd/cluster/read-replica/read_replica.go
cmd/nal/network_allow_list.go
cmd/util/util.go
cmd/vpc/peering/vpc_peering.go
cmd/vpc/vpc.go
docs/ybm_backup_delete.md
docs/ybm_cluster_delete.md
docs/ybm_cluster_network_endpoint_delete.md
docs/ybm_cluster_read-replica_delete.md
docs/ybm_network-allow-list_delete.md
docs/ybm_vpc_delete.md
docs/ybm_vpc_peering_delete.md
go.mod
go.sum

Add interactive prompt before deleting, including `--force` or `-f` to bypass the prompt

Adding prompt for deletion

---

cmd/cluster/create_cluster.go
cmd/cluster/encryption/encryption.go
cmd/cluster/encryption/encryptionutil.go
docs/ybm_cluster_create.md
docs/ybm_cluster_encryption_update.md

Summary:
Added GCP CMK support to these APIs:
1. Create cluster 
2. Update cluster CMK
Testing:
Tested cluster creation with CMK config for AWS and GCP providers via YBM CLI.
Tested update CMK API for both providers.

[CLOUDGA-13540][CLOUDGA-13541]: Added GCP CMK support to create cluster and update CMK API

---

cmd/permission/permissions.go
cmd/root.go
docs/ybm.md
docs/ybm_permission.md
docs/ybm_permission_list.md
internal/client/client.go

[CLOUDGA-13711] Add CLI support for listing available resource permissions

---

cmd/root.go
cmd/user/user.go
docs/ybm.md
docs/ybm_user.md
docs/ybm_user_delete.md
docs/ybm_user_invite.md
docs/ybm_user_list.md
docs/ybm_user_update.md
internal/client/client.go
internal/formatter/api_keys.go
internal/formatter/roles_full.go
internal/formatter/users.go

https://docs.google.com/document/d/11KyXXA1YTyTLNzHtZZIoQxOpdE7t106n5Anjk7uop0I/edit?usp=sharing

[CLOUDGA-13804] Users CLI support

---

cmd/backup_test.go
cmd/cluster_test.go
cmd/cmd_suite_test.go
cmd/test/fixtures/projects.json
cmd/vpc_test.go
go.mod
go.sum
internal/client/client.go

https://yugabyte.slack.com/archives/C04G8JB4GSD/p1685458105637379?thread_ts=1685413338.245219&cid=C04G8JB4GSD

Revert RBAC compatible project ID fetching till fix reaches prod

---

cmd/backup_test.go
cmd/cluster_test.go
cmd/cmd_suite_test.go
cmd/test/fixtures/projects.json
cmd/vpc_test.go
go.mod
go.sum
internal/client/client.go

Add this change back now that the related APIServer changes have reached PROD. Verified behaviour on cloud.yugabyte.com

Fetch project ID from listAccounts API

---

cmd/cluster/create_cluster.go
cmd/cluster/update_cluster.go
cmd/region/cloud_regions.go
cmd/region/instance_types.go
cmd/vpc/vpc.go
internal/formatter/api_keys.go
internal/formatter/cloud_regions.go
internal/formatter/resource_permissions.go
internal/formatter/roles.go
internal/formatter/roles_full.go
internal/formatter/users.go

Adding Azure in the help
Plus others fixing some static check issues.
To be merge once Azure is GA

Adding Azure help

---

go.mod
go.sum
internal/releases/releases.go

Fix Dependabot issue https://github.com/yugabyte/ybm-cli/security/dependabot/2
Update Google github lib to v53

Fix Dependabot issue 

---

cmd/cluster/encryption/encryption.go
cmd/cluster/encryption/encryptionutil.go

Modified the updateCmk api to allow adding CMK to non EAR enabled clusters.

[CLOUDGA-14373]: Add support for adding EAR to existing cluster 

---

cmd/cluster_test.go
internal/formatter/clusters.go

Added provider to the display.

Add provider

---

cmd/cluster/update_cluster.go

Fix iops panic
Do not wait when only the name changed as no task are created in the API

Fix update cluster when only the name is updated + One fix for a panic for iops

---

cmd/cluster/network/endpoint/list_endpoint.go
cmd/cluster_test.go
cmd/test/fixtures/one-cluster.json
internal/client/client.go
internal/cluster/cluster.go
internal/formatter/clusters_full.go
internal/formatter/endpoints.go

Can be merge,
Remove PRIVATE ENDPOINT FOR AZURE

Remove private endpoint for Azure

---

README.md
cmd/cluster/update_cluster.go
docs/ybm_cluster_update.md
internal/client/client.go

https://yugabyte.atlassian.net/browse/CLOUDGA-14851

[CLOUDGA-14851] Update CLI with new tracks

---

cmd/cluster_test.go
internal/formatter/clusters_full.go
internal/formatter/encryption.go

Summary:
Added CMK key status to the encryption details

[CLOUDGA-14957] Add key status to CMK details

---

cmd/cluster/encryption/encryption.go
cmd/util/feature_flags.go
docs/ybm_cluster_encryption.md
docs/ybm_cluster_encryption_update-state.md

Summary:
Reverted feature flag changes since the feature will go live this month.

[CLOUDGA-15945] Revert feature flag changes for CMK

---

cmd/metrics_exporter/metrics_exporter.go
docs/ybm_metrics-exporter_delete.md
go.mod
go.sum

Added force flag for deleting metrics exporter

---

cmd/cluster/create_cluster.go
docs/ybm_cluster_create.md

We added the Innovation track, need to update the help message.

Change the list of tracks

---

go.mod
go.sum

Should solve https://github.com/yugabyte/ybm-cli/security/dependabot/5

Update Golang crypto to 0.17

---

cmd/backup/policy/policy.go

Add required validations and prevent the CLI from crashing by handling errors for backup policies.

Handle errors and add validations for backup policies

---

cmd/backup/policy/policy.go
cmd/backup_shedule_test.go
cmd/test/fixtures/list-backup-schedules.json
internal/formatter/backup_policy_list.go

```
bash-5.2$ ./ybm backup policy list --cluster-name=remarkable-blackbird
Time Interval(days)   Days of the Week   Backup Start Time   Retention Period(days)   State
NA                    Mo                 10:10               2                        PAUSED
```

Display paused backup schedules and show state in the description

---

internal/client/client.go

These logs should be debug level, not info level.

[CLOUDGA-19510] Switch info logs to debug

---

cmd/backup/policy/policy.go
cmd/backup/policyv2/policy.go
cmd/backup_test.go
cmd/test/fixtures/backups.json
internal/formatter/backup.go

Improve list backup display

---

cmd/backup/backup.go
cmd/backup_test.go
cmd/test/fixtures/backup.json
docs/ybm.md
docs/ybm_backup_describe.md
docs/ybm_db-audit-logs-exporter.md
docs/ybm_db-audit-logs-exporter_assign.md
docs/ybm_db-audit-logs-exporter_list.md
internal/backup/backup.go
internal/formatter/backup.go
internal/formatter/backup_full.go

```
bash-5.2$ ./ybm backup describe --backup-id=5574d58f-68f1-4762-baa1-c2421cdb38b0
General
ID                                     Created On         Inc       Clusters        State
5574d58f-68f1-4762-baa1-c2421cdb38b0   2024-03-07,11:56   🟡        mirthful-mole   ✅
Type      Size(bytes)   Expire On          Duration
🧑        1176035       2024-03-08,11:56   2 mins
Databases/Keyspaces
Database/Keyspace   API Type
yugabyte            YSQL
my_keyspace         YCQL
```

Implement describe backup in CLI

---

cmd/cluster/pitr-config/pitr_config_ops.go
go.mod
go.sum

Check for restore DB PITR task during the corresponding command

Check for restore DB PITR task during the corresponding command

---

cmd/cluster/cluster.go

Hide cluster pitr-config sub command under FF

---

cmd/connection_pooling_test.go
cmd/pitr_config_test.go
cmd/test/fixtures/get-ycql-pitr-config.json
cmd/test/fixtures/get-ysql-pitr-config.json
cmd/test/fixtures/list-cluster-pitr-configs.json
go.mod
go.sum
internal/formatter/pitr_configs.go

Add Max allowed recovery time field for PITR commands
test plan:
UTs

[CLOUDGA-23129] Add Max allowed recovery time field for PITR commands

---

cmd/pitr_config_test.go
internal/formatter/pitr_configs.go

Remove backup interval seconds field PITR command output
Test plan:
UTs

Remove backup interval seconds field PITR command output

---

internal/formatter/nodes.go

Add json output for cluster node list command

Add json output for cluster node list command

---

cmd/cluster/connection-pooling/connection_pooling.go

[CLOUDGA-23292] [Revert]: Revert old commit for help in Enable/Disable CP commands

---

cmd/cluster/pitr-config/pitr_config_ops.go

https://docs.google.com/document/d/10CeiicZqZKmFhAztzcIHMaQKxSNgSJ8PmwP8voIwlwQ/edit?disco=AAABVKkYmco

PITR config min retention period is 2 days

---

cmd/cluster_test.go
internal/formatter/clusters.go
internal/formatter/clusters_full.go

Tested with cluster on devcloud

[CLOUDGA-23248] : CLI Get Cluster - Add CP Status

---

README.md

Add instructions to run unit tests locally.

Add instructions to run unit tests locally

---

cmd/cluster/dr/create_dr.go
cmd/cluster/dr/dr.go
cmd/cluster/dr/switchover_dr.go
cmd/cluster/dr/update_dr.go
cmd/cluster_test.go
internal/client/client.go

```
./ybm cluster dr update --dr-name sample-config --cluster-name alluring-goat --databases test1,test2
./ybm cluster dr switchover --cluster-name alluring-goat --dr-name sample-config
```

Support update and switchover DR

---

cmd/cluster/dr/failover_dr.go
cmd/cluster/dr/pause_dr.go
cmd/cluster/dr/restart_dr.go
cmd/cluster/dr/resume_dr.go
internal/client/client.go

```
./ybm cluster dr failover --cluster-name alluring-goat --dr-name sample-config-final-srinivas --safetimes test1=1729716937,test2=1729716937
./ybm cluster dr restart --cluster-name alluring-goat --dr-name sample-config-final-srinivas --databases test1,test2
./ybm cluster dr pause --cluster-name alluring-goat --dr-name sample-config-final-srinivas --duration 5
./ybm cluster dr resume --cluster-name alluring-goat --dr-name sample-config-final-srinivas
```

Support Failover, Restart, Pause and Resume

---

docs/ybm_cluster.md
docs/ybm_cluster_db-query-logging.md
docs/ybm_cluster_db-query-logging_describe.md
docs/ybm_cluster_db-query-logging_disable.md
docs/ybm_cluster_db-query-logging_enable.md
docs/ybm_cluster_db-query-logging_update.md

Added docs for DB query logging commands.
Generated via:
```bash
make doc
```

Added docs for DB query logging commands

---

cmd/cluster/update_cluster.go

Followup to the PR that removed root node info from cluster creation requests.
Tested:
```
./ybm cluster update --cluster-name daniel-test-cli-12 --cloud-provider GCP --cluster-tier Dedicated --region-info region=northamerica-northeast2,num-nodes=3,num-cores=4,disk-size-gb=200
```

[CLOUDGA-24982] Remove root node info from edit cluster

---

go.sum

```
bash-5.2$ ./ybm dr config describe  --config sample-config
Id                                     Name            Source Cluster   Target Cluster   Databases   State     Created On
10ca1adb-747c-47c6-8730-dea58c3d5936   sample-config   adept-egret      dreamy-swift     test1       Paused    2025-01-17,16:49
bash-5.2$ ./ybm dr config list
Id                                     Name            Source Cluster   Target Cluster   Databases   State     Created On
10ca1adb-747c-47c6-8730-dea58c3d5936   sample-config   adept-egret      dreamy-swift     test1       Paused    2025-01-17,16:49
```

Update go client to fix issue with DR in paused state

---

cmd/cluster/encryption/encryption.go
cmd/encryption_test.go

Refactored error message for EAR for better readability. 
For more context refer, 
https://github.com/yugabyte/yugabyte-db/pull/26070#discussion_r1964348948

Refactored error message for EAR
